# Generated by Django 5.2.17 on 2026-09-04 06:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPTTranslationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=255)),
                ('module_no', models.PositiveIntegerField()),
                ('lesson_id', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(max_length=100)),
                ('language_code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_file', models.CharField(blank=True, max_length=1000, null=True)),
                ('output_file', models.CharField(blank=True, max_length=1000, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
