# Generated by Django 5.2.17 on 2026-09-24 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ppttranslationjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognito_sub', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=240)),
                ('position', models.CharField(blank=True, max_length=240)),
                ('company', models.CharField(blank=True, max_length=240)),
                ('location', models.CharField(blank=True, max_length=240)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=255)),
                ('course_title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('current_module_id', models.CharField(blank=True, max_length=255, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.learnerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('current_chapter_id', models.CharField(blank=True, max_length=255, null=True)),
                ('current_slide_index', models.PositiveIntegerField(default=0)),
                ('qa_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('qa_passed', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.enrollment')),
            ],
            options={
                'ordering': ['order', 'module_id'],
            },
        ),
        migrations.CreateModel(
            name='ChapterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('current_slide_index', models.PositiveIntegerField(default=0)),
                ('current_slide_id', models.CharField(blank=True, max_length=255, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='api.moduleprogress')),
            ],
            options={
                'ordering': ['order', 'chapter_id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='api.moduleprogress')),
            ],
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('learner', 'course_id'), name='unique_learner_course_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='moduleprogress',
            constraint=models.UniqueConstraint(fields=('enrollment', 'module_id'), name='unique_enrollment_module_progress'),
        ),
        migrations.AddConstraint(
            model_name='chapterprogress',
            constraint=models.UniqueConstraint(fields=('module_progress', 'chapter_id'), name='unique_module_chapter_progress'),
        ),
    ]
