# Generated by Django 5.2.17 on 2026-09-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_learnerprofile_enrollment_moduleprogress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='candidate_number',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
