# Generated by Django 5.2.17 on 2026-09-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_learnerprofile_candidate_number_learnerprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
