# Generated by Django 5.2.17 on 2026-09-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_learnerprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapterprogress",
            name="highest_completed_slide_index",
            field=models.IntegerField(default=-1),
        ),
    ]
