# Generated by Django 5.2.17 on 2026-09-25 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_doubtticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubtAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio')], max_length=20)),
                ('s3_key', models.CharField(max_length=1024)),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('uploaded_by_cognito_sub', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.doubtticket')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
