# Generated by Django 5.2.17 on 2026-09-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_doubtattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="learnerprofile",
            name="active_session_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
