# Generated by Django 5.2.17 on 2026-09-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_learnerprofile_active_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="learning_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
